---
title: "Tunis demo Tuesday"
author: "Daniel"
date: "11/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = 'figures/')
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
```

# Materials and methods

We have three tables: samples, taxonomy and counts. The
latter one is a relation between the former two and shows 
the number of observations of a particular taxon in a 
particular sample.

The tables are read from tsv files, i.e. tab separated 
files using the ReadR `read_tsv()` function.

```{r read-data}
# Read the counts table
counts <- read_tsv(
  '../data/atacama-soils.asvtable.tsv',
  col_types = cols(
    .default = col_integer(), seqid = col_character()
  )
) %>%
  # Make the "wide" table "long"
  gather(sample, count, 2:67) %>%
  # Get rid of rows with zero counts
  filter(count > 0) %>%
  group_by(sample) %>%
  filter(sum(count) >= 1000) %>%
  ungroup() %>%
  group_by(sample) %>%
  mutate(relab = count/sum(count)) %>%
  ungroup()

# Read the samples table
samples <- read_tsv(
  '../data/sample_metadata_single_header.tsv',
  col_types = cols(
    .default = col_double(),
    SampleID = col_character(),
    BarcodeSequence = col_character(),
    LinkerPrimerSequence = col_character(),
    Elevation = col_integer(),
    ExtractGroupNo = col_character(),
    TransectName = col_character(),
    SiteName = col_character(),
    Depth = col_integer(),
    TOC = col_integer(),
    Vegetation = col_character(),
    Description = col_character()
  )
)

# Read the taxonomy
taxonomy <- read_tsv(
  '../data/taxonomy.tsv',
  col_types = cols(.default = col_character(), Confidence = col_double())
) %>%
  # Get rid of the "D_[0-9]__" string that starts each individual taxon
  mutate(
    Taxon = gsub('D_[0-9]__', '', Taxon)
  ) %>%
  # Separate the long taxon string into separate taxa
  separate(
    Taxon,
    c(
      'domain', 'phylum', 'class', 
      'order', 'family', 'genus', 'species'
    ),
    sep = ';',
    fill = 'right'
  ) %>%
  # Rename the Feature ID so it's seqid, like in the counts table
  rename(seqid = `Feature ID`)
```

```{r topphyla}
taxonomy <- taxonomy %>%
  left_join(
    counts %>%
      inner_join(taxonomy, by = 'seqid') %>%
      group_by(phylum, sample) %>%
      summarise(relab = sum(relab)) %>%
      summarise(mean_relab = mean(relab)) %>%
      ungroup() %>%
      top_n(10, mean_relab) %>%
      transmute(phylum, topphylum = phylum),
    by = 'phylum'
  ) %>%
  replace_na(list(topphylum = 'Other phyla'))
```


# Results

```{r}
samples %>%
  select(
    TransectName, Elevation, Depth, pH, TOC, EC, 
    AverageSoilRelativeHumidity,
    AverageSoilTemperature, PercentCover
  ) %>%
  gather(meastype, value, 2:ncol(.)) %>%
  filter(!is.na(value)) %>%
  ggplot(aes(x = TransectName, y = value)) +
  geom_violin() +
  geom_jitter(aes(colour = TransectName)) +
  coord_flip() +
  facet_wrap(~meastype, scales = 'free_x')
```

```{r rarefy}
# Calculate minimum size for any sample
minsize <- counts %>%
  group_by(sample) %>%
  summarise(count = sum(count)) %>%
  summarise(mincount = min(count)) %>%
  ungroup() %>%
  pull(mincount)
# Calculate rarified counts
counts <- counts %>%
  left_join(
    counts %>%
      select(-relab) %>%
      spread(seqid, count, fill = 0) %>%
      data.frame() %>%
      tibble::column_to_rownames('sample') %>%
      rrarefy(minsize) %>%
      data.frame() %>%
      tibble::rownames_to_column('sample') %>%
      gather(seqid, rcount, 2:ncol(.)) %>%
      filter(rcount > 0),
    by = c('seqid', 'sample')
  ) %>%
  replace_na(list(rcount = 0))
```

```{r plot-shannon}
counts %>%
  select(-count, -relab) %>%
  spread(seqid, rcount, fill = 0) %>%
  data.frame() %>%
  tibble::column_to_rownames('sample') %>%
  diversity() %>%
  data.frame(shannon = .) %>%
  tibble::rownames_to_column('sample') %>%
  ggplot(aes(x = sample, y = shannon)) +
  geom_point()
```

